### PR TITLE
Use Proper Assets append_path To Register Ember In Rails 4.2

### PR DESCRIPTION
**Pull request by HoyaBoya**
In Rails 4.2, Sprockets cannot find `ember` and raises an asset compile error in our application.js.

```
Sprockets::FileNotFound: couldn't find file 'ember' with type 'application/javascript'
/Users/csun/Projects/blue_apron/blueapron.com/app/assets/javascripts/blueadmin/application.js.coffee
```

The observation here is that this does work in later versions of `ember-rails`. Yet we can't use it because of Handlebar versioning and general legitimate phobia of jumping too many Ember versions. So let's bring what works into our fork, which is using `config.assets.configure` vs `config.assets` to append the Gem folders into the asset path so that Ember can be loaded by Sprockets.

I've tested the branch of the branch locally, and I can confirm asset-compile works.

/cc @blueapron/rails4

### CODE REVIEW

**Comment by travisofthenorth** [comment]
Very neat. LGTM 👍

**Comment by HoyaBoya** [comment]
The Circle CI build is here to verify that we are about 200 less errors with the Ember compile issues.

https://circleci.com/gh/blueapron/blueapron.com/33387

**Comment by HoyaBoya** [comment]
screen shot 2016-05-10 at 11 54 39 am

And tests are cleaner.

@prsimp anything else you want me to do here? Let me push to `travis.core` to ensure that we can also hit Blue Admin.

**Comment by HoyaBoya** [comment]
Oh what the heck. So we end up with the same handlebar versioning issues as if we were on the `0.18.5` version of `ember-rails`. What the heck.

screen shot 2016-05-10 at 12 04 06 pm

**Comment by HoyaBoya** [comment]
Merging this in. Thanks @travisofthenorth.

**Pull request merged**
